extends Node
## Campaign progress: which chapter you're on, gold, loot, upgrades bought from Tomás,
## relic fragments found, and who you've already talked to. Saved to user://save.cfg
## at every chapter start and after every purchase, so CONTINUE picks up there.
## Test maps (proving_grounds, testbed, arena) are only reachable with `-- --map <id>`.

const MAIN := "res://scenes/main.tscn"
const TITLE := "res://scenes/menu.tscn"
const CAMP := "res://scenes/camp.tscn"
const INTRO := "res://scenes/intro.tscn"
const SAVE := "user://save.cfg"

## Upgrades Tomás sells. costs: one entry per level.
const UPGRADES := {
	"hat": {"name": "Lined Stetson", "desc": "+1 health", "costs": [60, 140]},
	"bandolier": {"name": "Bandolier", "desc": "+1 grenade carried and on every restock", "costs": [50, 110]},
	"loader": {"name": "Speed Loader", "desc": "Reload 40% faster", "costs": [90]},
	"whip": {"name": "Long Whip", "desc": "+25% whip reach", "costs": [80]},
	"boots": {"name": "Hobnail Boots", "desc": "Cracked rock breaks in two kicks, not three", "costs": [45]},
}

var chapter := 0
var gore_on := true
## Loot carried: [{seed, kind, rarity, name, value, count}], plus gold.
var inventory: Array = []
var gold := 0
var upgrades := {}  # id -> level
var fragments := {}  # map id -> [fragment indices found]
var flags := {}  # conversation ids already played, one-off rewards...
signal loot_changed
var music_vol := 0.7
var sfx_vol := 1.0
## This level's run, for the summary.
var run := {}
## Level -> music track (assets/music/<name>.mp3, generated by tools/gen_music.py).
const MUSIC := {"proving_grounds": "canyon", "testbed": "canyon", "dry_gulch": "canyon", "rattler_mesa": "mesa",
		"bandit_mine": "mine", "canopy_run": "jungle", "sunken_temple": "temple", "idol_chamber": "temple", "arena": "canyon"}


func _ready() -> void:
	UI.setup_fonts()
	_load_settings()
	# Screenshots for review: -- --snap <dir> [--every s] [--count n] (needs a window).
	var args := OS.get_cmdline_user_args()
	var i := args.find("--snap")
	if i >= 0:
		var every := float(args[args.find("--every") + 1]) if args.has("--every") else 1.0
		var count := int(args[args.find("--count") + 1]) if args.has("--count") else 5
		_snap(args[i + 1], every, count)


func _snap(dir: String, every: float, count: int) -> void:
	DirAccess.make_dir_recursive_absolute(dir)
	for k in count:
		await get_tree().create_timer(every, true, false, true).timeout
		var scene: String = get_tree().current_scene.name if get_tree().current_scene else "none"
		get_viewport().get_texture().get_image().save_png(dir.path_join("%s_%02d.png" % [scene, k]))
	get_tree().quit()


func map_id() -> String:
	var args := OS.get_cmdline_user_args()
	var i := args.find("--map")
	if i >= 0 and i + 1 < args.size():
		return args[i + 1]
	return Story.CHAPTERS[chapter]["map"]


func is_test_map() -> bool:
	return Story.chapter_index(map_id()) < 0


func up(id: String) -> int:
	return upgrades.get(id, 0)


func add_gold(n: int) -> void:
	gold += n
	run["gold"] = run.get("gold", 0) + n
	loot_changed.emit()


func add_item(it: Item) -> void:
	for e in inventory:
		if e["name"] == it.name:
			e["count"] += 1
			loot_changed.emit()
			return
	var d := it.to_dict()
	d["count"] = 1
	inventory.append(d)
	loot_changed.emit()


func loot_value() -> int:
	var v := gold
	for e in inventory:
		v += int(e["value"]) * int(e["count"])
	return v


## Selling treasure to Tomás turns the haul into spendable gold.
func sell_all() -> int:
	var v := 0
	for e in inventory:
		v += int(e["value"]) * int(e["count"])
	inventory.clear()
	gold += v
	loot_changed.emit()
	save()
	return v


func buy(id: String) -> bool:
	var costs: Array = UPGRADES[id]["costs"]
	var lvl := up(id)
	if lvl >= costs.size() or gold < costs[lvl]:
		return false
	gold -= costs[lvl]
	upgrades[id] = lvl + 1
	loot_changed.emit()
	save()
	return true


func found_fragment(map: String, idx: int) -> bool:
	var got: Array = fragments.get(map, [])
	if idx in got:
		return false
	got.append(idx)
	fragments[map] = got
	run["fragments"] = run.get("fragments", 0) + 1
	return true


func has_fragment(map: String, idx: int) -> bool:
	return idx in fragments.get(map, [])


func fragment_total() -> int:
	var n := 0
	for m in fragments:
		n += (fragments[m] as Array).size()
	return n


# --- Flow ------------------------------------------------------------------------

func has_save() -> bool:
	return FileAccess.file_exists(SAVE)


func new_game() -> void:
	chapter = 0
	inventory.clear()
	gold = 0
	upgrades.clear()
	fragments.clear()
	flags.clear()
	start_chapter()


func continue_game() -> void:
	load_game()
	start_chapter()


func start_chapter() -> void:
	run = {"t0": Time.get_ticks_msec(), "kills": 0, "deaths": 0, "gold": 0, "fragments": 0}
	save()
	get_tree().change_scene_to_file.call_deferred(MAIN)


## The level's exit was reached: on to camp (or the ending).
func level_done() -> void:
	if is_test_map():
		get_tree().change_scene_to_file.call_deferred(TITLE)
		return
	chapter += 1
	save()
	get_tree().change_scene_to_file.call_deferred(CAMP)


func campaign_over() -> bool:
	return chapter >= Story.CHAPTERS.size()


func title() -> void:
	get_tree().paused = false
	get_tree().change_scene_to_file.call_deferred(TITLE)


# --- Save ------------------------------------------------------------------------

func save() -> void:
	var c := ConfigFile.new()
	c.set_value("game", "chapter", chapter)
	c.set_value("game", "gold", gold)
	c.set_value("game", "inventory", inventory)
	c.set_value("game", "upgrades", upgrades)
	c.set_value("game", "fragments", fragments)
	c.set_value("game", "flags", flags)
	_settings_into(c)
	c.save(SAVE)


func load_game() -> void:
	var c := ConfigFile.new()
	if c.load(SAVE) != OK:
		return
	chapter = mini(c.get_value("game", "chapter", 0), Story.CHAPTERS.size() - 1)
	gold = c.get_value("game", "gold", 0)
	inventory = c.get_value("game", "inventory", [])
	upgrades = c.get_value("game", "upgrades", {})
	fragments = c.get_value("game", "fragments", {})
	flags = c.get_value("game", "flags", {})


func save_settings() -> void:
	var c := ConfigFile.new()
	c.load(SAVE)
	_settings_into(c)
	c.save(SAVE)
	Audio.set_volumes(music_vol, sfx_vol)


func _settings_into(c: ConfigFile) -> void:
	c.set_value("settings", "gore", gore_on)
	c.set_value("settings", "music", music_vol)
	c.set_value("settings", "sfx", sfx_vol)


func _load_settings() -> void:
	var c := ConfigFile.new()
	if c.load(SAVE) == OK:
		gore_on = c.get_value("settings", "gore", true)
		music_vol = c.get_value("settings", "music", 0.7)
		sfx_vol = c.get_value("settings", "sfx", 1.0)
	Audio.set_volumes.call_deferred(music_vol, sfx_vol)
